apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: {{ .Values.name }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ .Values.name }}
  wildcardPolicy: None
