apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "digital-marketplace.labels" . | indent 4}}
spec:
  ports:
  - name: {{ .Values.name }}
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.name }}
  sessionAffinity: None
  type: ClusterIP
